language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: false
      mono: latest
      dotnet: 2.0.0
    - os: osx # OSX 10.12
      osx_image: xcode9.1
      dotnet: 2.0.0
      mono: latest
      sudo: false

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then wget http://http.us.debian.org/debian/pool/main/l/lz4/liblz4-1_0.0~r131-2+b1_amd64.deb; sudo dpkg -i liblz4-1_0.0~r131-2+b1_amd64.deb; else brew install lz4; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then objdump -T /usr/lib/x86_64-linux-gnu/liblz4.so.1; fi

script: 
  - dotnet --info
  - ./build.sh All

branches:
  except:
    - gh-pages